INSERT INTO ACTOR(DOB, FIRSTNAME, GENDER, LASTNAME) VALUES ('1987-11-10', 'Some', 'Male', 'GUY');
INSERT INTO ACTOR(DOB, FIRSTNAME, GENDER, LASTNAME) VALUES ('1989-11-10', 'Some', 'Male', 'Other Guy');
INSERT INTO ACTOR(DOB, FIRSTNAME, GENDER, LASTNAME) VALUES ('1971-11-10', 'Some', 'Male', 'Further Guy');
INSERT INTO CINEMA(CITY, NAME, OPENINGTIMES) VALUES ('Manchester', 'QAC Manch', 'Times');
INSERT INTO CINEMA(CITY, NAME, OPENINGTIMES) VALUES ('Liverpool', 'QAC Liver', 'OtherTimes');
INSERT INTO CINEMA(CITY, NAME, OPENINGTIMES) VALUES ('Dorset', 'QAC Dorset', 'FurtherTimes');
INSERT INTO MOVIE(CERTIFICATION, DESCRIPTION, DURACTION, GENRE, POSTERURL, RELEASEDATE, TILLE) 
			VALUES ('PG', 'A film', '120m', 'Fantasy', 'AURL', '2012-11-15', 'A Film');
INSERT INTO MOVIE(CERTIFICATION, DESCRIPTION, DURACTION, GENRE, POSTERURL, RELEASEDATE, TILLE) 
		VALUES ('18', 'Another film', '120m', 'Action', 'AnotherURL', '2015-11-15', 'A other Film');
INSERT INTO MOVIE(CERTIFICATION, DESCRIPTION, DURACTION, GENRE, POSTERURL, RELEASEDATE, TILLE) 
		VALUES ('15', 'A further film', '120m', 'Horror', 'AFurtherURL', '2016-11-15', 'A furtherFilm');
INSERT INTO SCREEN(ISDIRECTORSBOX, NOOFSEATS, SCREENNUM, SCREENTYPE, CINEMA_IDCINEMA) 
		VALUES ('false', '120', '1', '3D', 1);
INSERT INTO SCREEN(ISDIRECTORSBOX, NOOFSEATS, SCREENNUM, SCREENTYPE, CINEMA_IDCINEMA) 
		VALUES ('true', '50', '1', '3D', 2);
INSERT INTO SCREEN(ISDIRECTORSBOX, NOOFSEATS, SCREENNUM, SCREENTYPE, CINEMA_IDCINEMA) 
		VALUES ('false', '120', '1', '3D', 3);
INSERT INTO SHOWING(AVAILABLESEATS, SHOWINGTYPE, STARTTIME, MOVIE_IDMOVIE, SHOWING_IDSHOWING) 
		VALUES ('119', '3D', '7pm', 1, 1);
INSERT INTO SHOWING(AVAILABLESEATS, SHOWINGTYPE, STARTTIME, MOVIE_IDMOVIE, SHOWING_IDSHOWING) 
		VALUES ('49', '3D', '7pm', 2, 2);
INSERT INTO SHOWING(AVAILABLESEATS, SHOWINGTYPE, STARTTIME, MOVIE_IDMOVIE, SHOWING_IDSHOWING) 
		VALUES ('119', '3D', '7pm', 3, 3);
INSERT INTO USER(DOB, EMAIL, FIRSTNAME, LASTNAME, PASSWORD) 
		VALUES ('2001-11-11', 'anemail', 'Some', 'Guy', 'hashpass');
INSERT INTO USER(DOB, EMAIL, FIRSTNAME, LASTNAME, PASSWORD) 
		VALUES ('1999-11-11', 'anotheremail', 'Some', 'Other Guy', 'hashpass');
INSERT INTO USER(DOB, EMAIL, FIRSTNAME, LASTNAME, PASSWORD) 
		VALUES ('1989-11-11', 'anfurtheremail', 'Some', 'Other Guy', 'hashpass');
INSERT INTO TICKET(TICKETTYPE, SHOWING_IDSHOWING, USER_IDUSER) 
		VALUES ('Normal', 1, 1);
INSERT INTO TICKET(TICKETTYPE, SHOWING_IDSHOWING, USER_IDUSER) 
		VALUES ('Normal', 2, 2);
INSERT INTO TICKET(TICKETTYPE, SHOWING_IDSHOWING, USER_IDUSER) 
		VALUES ('Normal', 3, 3);
INSERT INTO ACTOR_HAS_MOVIE(MOVIE_IDMOVIE, ACTOR_IDACTOR) 
		VALUES (1, 1);
INSERT INTO ACTOR_HAS_MOVIE(MOVIE_IDMOVIE, ACTOR_IDACTOR) 
		VALUES (2, 2);
INSERT INTO ACTOR_HAS_MOVIE(MOVIE_IDMOVIE, ACTOR_IDACTOR) 
		VALUES (3, 3);